source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
 
pod 'Alamofire', '~> 3.0'
 
target ‘Twinder’ do
	pod 'Alamofire', '~> 3.0'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'ObjectMapper', '~> 1.1'
	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
end
